image: yogendra/ybdb-workshop-gitpod-ws:2.20.0.0-b76
tasks:
  - name: ybdb
    before: gp open ${GITPOD_REPO_ROOT}/ws/iloop/README.md
    env:
      DATA_PATH: ybdb
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/${DATA_PATH}
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/${DATA_PATH} --advertise_address=$HOST --cloud_location=ybcloud.pandora.az1 --background=true
  - name: ysqlsh
    command: |
      gp ports await ${YSQL_SOCK} && sleep 2
      ysqlsh -f ${GITPOD_REPO_ROOT}/ws/iloop/init.sql
      ysqlsh
  - name: dev-inner-loop
    env:
      APP_ID: ybdbapp
    init: |
      npm install -g generator-jhipster-yugabytedb
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/${APP_ID} && cd ${GITPOD_REPO_ROOT}/${APP_ID}
      echo "Run 'ybdb | yugabytedb' to get started!"

vscode:
  extensions:
    - ms-azuretools.vscode-docker

# exposed ports
ports:
  - port: 7000
    name: yb-master-web
    onOpen: ignore
  - port: 9000
    name: yb-tserver-web
    onOpen: ignore
  - port: 7100
    name: yb-master-rpc
    onOpen: ignore
  - port: 9100
    name: yb-tserver-rpc
    onOpen: ignore
  - port: 5433
    name: ysql
    onOpen: ignore
  - port: 13000
    name: ysql-api
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 12000
    name: ycql-api
    onOpen: ignore
  - port: 8080
    name: app
    onOpen: ignore
  - port: 15433
    name: yugabyted-ui
    onOpen: ignore
