image: yogendra/ybdb-workshop-gitpod-ws:2.20.0.0-b76
tasks:
  - name: ybdb
    before: gp open ${GITPOD_REPO_ROOT}/ws/scale-v2/README.md
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/ybdb
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1 --advertise_address=$HOST_LB --tserver_flags=ysql_num_shards_per_tserver=2,yb_num_shards_per_tserver=2 --cloud_location=ybcloud.pandora.az1 --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd2 --advertise_address=$HOST_LB2 --join=$HOST_LB --tserver_flags=ysql_num_shards_per_tserver=2,yb_num_shards_per_tserver=2 --cloud_location=ybcloud.pandora.az2 --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd3 --advertise_address=$HOST_LB3 --join=$HOST_LB --tserver_flags=ysql_num_shards_per_tserver=2,yb_num_shards_per_tserver=2 --cloud_location=ybcloud.pandora.az3 --fault_tolerance=zone
      yugabyted configure data_placement --fault_tolerance=zone --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1
      gp sync-done ybdb
  - name: ysqlsh
    command: |
      gp sync-await ybdb && gp ports await 5433 && sleep 2
      ysqlsh
  - name: ycqlsh
    command: |
      gp sync-await ybdb && gp ports await 9042 && sleep 2
      ycqlsh

  - name: download-load-app
    command: |
      wget https://github.com/YugabyteDB-Samples/yb-workload-simulator/releases/download/v0.0.7/yb-workload-sim-0.0.7.jar
      gp sync-done load-app
      exit 0
  - name: ysql-load
    env:
      SECRET: yugabyte
      USER: yugabyte
    command: |
      gp sync-await load-app && gp sync-await ybdb && sleep 2
      java -jar yb-workload-sim-0.0.7.jar  \
        --spring.datasource.hikari.data-source-properties.serverName=${HOST_LB} \
        --spring.datasource.hikari.data-source-properties.portNumber=${YSQL_SOCK} \
        --spring.datasource.hikari.data-source-properties.additionalEndpoints=${HOST_LB2}:${YSQL_SOCK},${HOST_LB3}:${YSQL_SOCK} \
        --spring.datasource.hikari.data-source-properties.topologyKeys=ybcloud.pandora.\*  \
        --spring.datasource.hikari.username=${USER}  \
        --spring.datasource.hikari.password=${SECRET}

  - name: ybdb-scale
    env:
      SCRIPT_PATH: ws/scale
    before: |
      sudo apt-get install pv -y
      curl -ssLo ${GITPOD_REPO_ROOT}/${SCRIPT_PATH}/pscript https://raw.githubusercontent.com/paxtonhare/demo-magic/master/demo-magic.sh
      chmod +x ${GITPOD_REPO_ROOT}/${SCRIPT_PATH}/pscript
      chmod +x ${GITPOD_REPO_ROOT}/${SCRIPT_PATH}/prompt.sh
      cd ${GITPOD_REPO_ROOT}/${SCRIPT_PATH}
    command: |
      gp sync-await ybdb
      bash prompt.sh

vscode:
  extensions:
    - ms-azuretools.vscode-docker

# exposed ports
ports:
  - port: 7000
    name: yb-master-web
    onOpen: ignore
  - port: 9000
    name: yb-tserver-web
    onOpen: ignore
  - port: 7100
    name: yb-master-rpc
    onOpen: ignore
  - port: 9100
    name: yb-tserver-rpc
    onOpen: ignore
  - port: 5433
    name: ysql
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 13000
    name: ysql-api
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 12000
    name: ycql-api
    onOpen: ignore
  - port: 15433
    name: yugabyted-ui
    onOpen: ignore
  - port: 8080
    name: workload-simulator
    onOpen: ignore
