image: yogendra/ybdb-workshop-gitpod-ws:2.20.0.0-b76
tasks:
  - name: ybdb
    before: gp open ${GITPOD_REPO_ROOT}/ws/xcluster/README.md
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/ybdb
      echo "=========== C1 - Create universe"
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1 --advertise_address=$HOST_LB --cloud_location=ybcloud.pandora.az1 --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd2 --advertise_address=$HOST_LB2 --join=$HOST_LB --cloud_location=ybcloud.pandora.az2 --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd3 --advertise_address=$HOST_LB3 --join=$HOST_LB --cloud_location=ybcloud.pandora.az3 --fault_tolerance=zone
      yugabyted configure data_placement --fault_tolerance=zone --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1
      
      echo "=========== C1 - Setup demo DB"
      echo -n  "Wait for C1 to be ready" ; until /usr/local//yugabyte/postgres/bin/pg_isready -h $HOST_LB &>> /dev/null  ; do echo -n . ; done;  echo " - done" ;
      ysqlsh -h $HOST_LB -c 'create database demo;'
      ysqlsh -h $HOST_LB -d demo -f /usr/local/yugabyte/share/northwind_ddl.sql

      echo "=========== C2 - Create universe"
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd4 --advertise_address=$HOST_LB4 --cloud_location=ybcloud.centaury.az1 --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd5 --advertise_address=$HOST_LB5 --join=$HOST_LB4 --cloud_location=ybcloud.centaury.az2 --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd6 --advertise_address=$HOST_LB6 --join=$HOST_LB4 --cloud_location=ybcloud.centaury.az3 --fault_tolerance=zone
      yugabyted configure data_placement --fault_tolerance=zone --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd4
      
      echo "=========== C2 - Setup demo DB"
      echo -n  "Wait for C2 to be ready" ; until /usr/local//yugabyte/postgres/bin/pg_isready -h $HOST_LB4 &>> /dev/null  ; do echo -n . ; done;  echo " - done" ;
      ysqlsh -h $HOST_LB4 -c 'create database demo;'
      ysqlsh -h $HOST_LB4 -d demo -f /usr/local/yugabyte/share/northwind_ddl.sql


      echo "=========== C1 -  Setup replication to C1 ->- C2"
      target_master=$HOST_LB4
      source_master=$HOST_LB:7100
      source_master_list=$HOST_LB:7100,$HOST_LB2:7100,$HOST_LB3:7100
      cluster_uuid=$(yb-admin -init_master_addrs $source_master get_universe_config | jq -r '.clusterUuid')
      table_ids=$(yb-admin -init_master_addrs $source_master list_tables include_table_id | grep demo | grep -Ev demo.pg_\|demo.sql_  | awk {'print $2'} | tr \\n , | sed 's/,$//')
      yb-admin -init_master_addrs $target_master setup_universe_replication $cluster_uuid-xcluster $source_master_list $table_ids

      echo "=========== C2 -  Setup replication to C1 -<- C2"
      target_master=$HOST_LB
      source_master=$HOST_LB4:7100
      source_master_list=$HOST_LB4:7100,$HOST_LB5:7100,$HOST_LB6:7100
      cluster_uuid=$(yb-admin -init_master_addrs $source_master get_universe_config | jq -r '.clusterUuid')
      table_ids=$(yb-admin -init_master_addrs $source_master list_tables include_table_id | grep demo | grep -Ev demo.pg_\|demo.sql_  | awk {'print $2'} | tr \\n , | sed 's/,$//')
      yb-admin -init_master_addrs $target_master setup_universe_replication $cluster_uuid-xcluster $source_master_list $table_ids

      echo "=========== C1 - Load Data"
      ysqlsh -h $HOST_LB -d demo -f /usr/local/yugabyte/share/northwind_data.sql

      echo "=========== C1 - check data"
      ysqlsh -h $HOST_LB -d demo -c 'select count(*) from categories;'

      echo "=========== C2 - check data"
      ysqlsh -h $HOST_LB2 -d demo -c 'select count(*) from categories;'
      gp sync-done ybdb

  - name: C1-ysqlsh
    command: |
      gp sync-await ybdb
      ysqlsh -h $HOST_LB
  - name: C1-ysqlsh
    command: |
      gp sync-await ybdb
      ysqlsh -h $HOST_LB4

vscode:
  extensions:
    - ms-azuretools.vscode-docker

# exposed ports
ports:
  - port: 7000
    name: yb-master-web
    onOpen: ignore
  - port: 9000
    name: yb-tserver-web
    onOpen: ignore
  - port: 7100
    name: yb-master-rpc
    onOpen: ignore
  - port: 9100
    name: yb-tserver-rpc
    onOpen: ignore
  - port: 5433
    name: ysql
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 13000
    name: ysql-api
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 12000
    name: ycql-api
    onOpen: ignore
  - port: 15433
    name: yugabyted-ui
    onOpen: ignore
