image:
  file: .ybdb.Dockerfile
tasks:
  - name: ybdb
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/ybdb
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1 --advertise_address=$HOST_LB --cloud_location=ybcloud.pandora.az1 --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd2 --advertise_address=$HOST_LB2 --join=$HOST_LB --cloud_location=ybcloud.pandora.az2 --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd3 --advertise_address=$HOST_LB3 --join=$HOST_LB --cloud_location=ybcloud.pandora.az3 --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd4 --advertise_address=$HOST_LB4 --join=$HOST_LB --cloud_location=ybcloud.pandora.az1 --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd5 --advertise_address=$HOST_LB5 --join=$HOST_LB --cloud_location=ybcloud.pandora.az2 --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd6 --advertise_address=$HOST_LB6 --join=$HOST_LB --cloud_location=ybcloud.pandora.az3 --fault_tolerance=zone
      yugabyted configure data_placement --fault_tolerance=zone --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1
      gp sync-done ybdb
  - name: ysqlsh
    command: |
      gp sync-await ybdb && gp ports await ${YSQL_SOCK} && sleep 2
      ysqlsh
  - name: ycqlsh
    command: |
      gp sync-await ybdb && gp ports await ${YCQL_SOCK} && sleep 2
      ycqlsh

  - name: download-load-app
    command: |
      wget https://github.com/yugabyte/yb-sample-apps/releases/download/v1.4.1/yb-sample-apps.jar
      gp sync-done load-app
      exit 0
  - name: ysql-load
    env:
      SECRET: yugabyte
      USER: yugabyte
    command: |
      gp sync-await load-app && gp sync-await ybdb && sleep 2
      java -jar ./yb-sample-apps.jar --workload SqlInserts --num_reads 15000000 --num_writes 2000000 --num_threads_read 5 --num_threads_write 2 --nodes ${HOST_LB}:${YSQL_SOCK},${HOST_LB2}:${YSQL_SOCK},${HOST_LB3}:${YSQL_SOCK} --password ${SECRET} --username ${USER}
  - name: ycql-load
    env:
      SECRET: yugabyte
      USER: yugabyte
    command: |
      gp sync-await load-app && gp sync-await ybdb && sleep 2
      java -jar ./yb-sample-apps.jar --workload CassandraKeyValue --num_reads 15000000 --num_writes 2000000 --num_threads_read 5 --num_threads_write 2 --nodes ${HOST_LB}:${YCQL_SOCK},${HOST_LB2}:${YCQL_SOCK},${HOST_LB3}:${YCQL_SOCK} --password ${SECRET} --username ${USER}

  - name: az-fd
    env:
      SCRIPT_PATH: init-ft
    before: |
      sudo apt-get install pv -y
      curl -ssLo ${GITPOD_REPO_ROOT}/${SCRIPT_PATH}/pscript https://raw.githubusercontent.com/paxtonhare/demo-magic/master/demo-magic.sh
      chmod +x ${GITPOD_REPO_ROOT}/${SCRIPT_PATH}/pscript
      chmod +x ${GITPOD_REPO_ROOT}/${SCRIPT_PATH}/prompt.sh
      cd ${GITPOD_REPO_ROOT}/${SCRIPT_PATH}
    command: |
      gp sync-await ybdb
      bash prompt.sh

vscode:
  extensions:
    - ms-azuretools.vscode-docker

# exposed ports
ports:
  - port: 7000
    name: yb-master-web
    onOpen: ignore
  - port: 9000
    name: yb-tserver-web
    onOpen: ignore
  - port: 7100
    name: yb-master-rpc
    onOpen: ignore
  - port: 9100
    name: yb-tserver-rpc
    onOpen: ignore
  - port: 5433
    name: ysql
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 13000
    name: ysql-api
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 12000
    name: ycql-api
    onOpen: ignore
